services:
  db:
    image: postgres
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgres
    environment:
      - POSTGRES_DATABASE=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432

  backend:
    build: backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
    depends_on:
      - db

  proxy:
    build: proxy
    ports:
      - 8080:80
    depends_on:
      - backend

volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt